export default {
  BASEMAPS: {
    "STREETS": "streets",
    "SATELLITE": "satellite",
    "HYBRID": "hybrid",
    "TOPO": "topo",
    "GRAY": "gray",
    "DARK_GRAY": "dark-gray",
    "OCEANS": "oceans",
    "NATIONAL_GEOGRAPHIC": "national-geographic",
    "TERRAIN": "terrain",
    "OSM": "osm",
    "DARK_GRAY_VECTOR": "dark-gray-vector",
    "GRAY_VECTOR": "gray-vector",
    "STREETS_VECTOR": "streets-vector",
    "TOPO_VECTOR": "topo-vector",
    "STREETS_NIGHT_VECTOR": "streets-night-vector",
    "STREETS_RELIEF_VECTOR": "streets-relief-vector",
    "STREETS_NAVIGATION_VECTOR": "streets-navigation-vector"
  },
  TRI_FIELDS: [
    "TRI_FACILITY_ID",
    "FACILITY_NAME",
    "STREET_ADDRESS",
    "CITY_NAME",
    "COUNTY_NAME",
    "STATE_ABBR",
    "ZIP_CODE"
  ],
  STATES: {
    "AK" : "Alaska",
    "AL" : "Alabama",
    "AR" : "Arkansas",
    "AS" : "American Samoa",
    "AZ" : "Arizona",
    "CA" : "California",
    "CO" : "Colorado",
    "CT" : "Connecticut",
    "DC" : "District of Columbia",
    "DE" : "Delaware",
    "FL" : "Florida",
    "GA" : "Georgia",
    "GU" : "Guam",
    "HI" : "Hawaii",
    "IA" : "Iowa",
    "ID" : "Idaho",
    "IL" : "Illinois",
    "IN" : "Indiana",
    "KS" : "Kansas",
    "KY" : "Kentucky",
    "LA" : "Louisiana",
    "MA" : "Massachusetts",
    "MD" : "Maryland",
    "ME" : "Maine",
    "MI" : "Michigan",
    "MN" : "Minnesota",
    "MO" : "Missouri",
    "MS" : "Mississippi",
    "MT" : "Montana",
    "NC" : "North Carolina",
    "ND" : "North Dakota",
    "NE" : "Nebraska",
    "NH" : "New Hampshire",
    "NJ" : "New Jersey",
    "NM" : "New Mexico",
    "NV" : "Nevada",
    "NY" : "New York",
    "OH" : "Ohio",
    "OK" : "Oklahoma",
    "OR" : "Oregon",
    "PA" : "Pennsylvania",
    "PR" : "Puerto Rico",
    "RI" : "Rhode Island",
    "SC" : "South Carolina",
    "SD" : "South Dakota",
    "TN" : "Tennessee",
    "TX" : "Texas",
    "UT" : "Utah",
    "VA" : "Virginia",
    "VI" : "Virgin Islands",
    "VT" : "Vermont",
    "WA" : "Washington",
    "WI" : "Wisconsin",
    "WV" : "West Virginia",
    "WY" : "Wyoming"
  }
}
